{% set version = "1.5.0" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: 2e44532500f3720e5b7b4e3ac483fa6e0c5e3feadc132791f08b6ed4ee9ca704

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    # Pinning Django to versions not failing the testsuite
    - django ==1.8  # [py3k]
    - django <=1.8  # [py2k]
  
test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
