{% set name = "django-extensions" %}
{% set version = "1.8.1" %}
{% set sha256 = "c8b39b1c929785286a5ec5f38f9c90f7481fbe51a036161d1b622e7a6abaa1d6" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six >=1.2
    - django >=1.7

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
