{% set version = "2.2.5" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: b58320d3fe3d6ae7d1d8e38959713fa92272f4921e662d689058d942a5b444f7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    - django >=1.7
    - typing

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
