{% set name = "django-extensions" %}
{% set version = "1.9.1" %}
{% set sha256 = "b562fd29acbf5d9b18a1c8605f1009719357b739e3a869a4bd4c7be223ace1cc" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six >=1.2
    - django >=1.7

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
