{% set name = "django-extensions" %}

{% set version = "2.1.0" %}
{% set sha256 = "c3c8524056ab1174c6fc769b0599e60f7e7797ce34f38db2effc48885a0a982c" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    - django >=1.7
    - typing

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
