{% set version = "3.1.3" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: 5f0fea7bf131ca303090352577a9e7f8bfbf5489bd9d9c8aea9401db28db34a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=2.2

test:
  imports:
    - django_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: Extensions for Django.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
