{% set version = "2.2.2" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: 867e87b611a47afa06e78aad28e9c5be0fdc581a59f851f83c3b7490675029e6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    - django >=1.7
    - typing

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
