{% set version = "2.2.3" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: 526d84b16ee180e45e2305f19d3e01ff3f9f513133839c0b4478b97310ade82a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    - django >=1.7
    - typing

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
