{% set version = "2.1.5" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: a607459e5fa8c579a672131b63366fa52fab80adb2a862d362f5fb48cd2d2cac

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six >=1.2
    - django >=1.7
    - typing

test:
  imports:
    - django_extensions

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: 'Extensions for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
