{% set name = "django-extensions" %}
{% set version = "1.7.3" %}
{% set sha256 = "42756a62518ecb7e64e77bdf29a01515d1ddacc5bcaec2f5ae381275e65b7c10" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/django-extensions/django-extensions/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six >=1.2
        - django >=1.7

test:
    imports:
        - django_extensions

about:
    home: http://github.com/django-extensions/django-extensions
    license: MIT
    summary: Extensions for Django

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
