travis:
  secure:
    BINSTAR_TOKEN: VeRwbmcbLpkvSS7Ho1O9iRcyVzGL1l74qw3Wk6LYlpzrCNtVMKd+0k/4XPFQYAkqm3L5G2TWiafgZ9J9aEOrvyp7SjduaNN4qgcEDMfKwki6tz+0+8+FJztFd/l9IVFCLls2YisaZQPuoyourQLPDO1nESz7zWj1Y3pnpI26yVjKjMRIG8zAonhxk1Q4omJuXntwHYg/ZwVDvRWbhnnfU1S5nR8PPoYlrLxlQwF4eYN2ne8c2EEUyqpE+53nadM1c9lW1nThy7VmFLvXBQ1IJrPiZxUIU4Fx5kf/C5kbvgkUWLRRH9kIsCazijw10MuBcVu3GPjnkFOmX6YTOp7+YBdYTAsKJS3ZcKbo8t9Lxh1zOT/TYMrppfi9i/d/fi7Elg/15pMHaD9o4BnddYHotdWy/+rs2qVp8lWTHwde1GtUuyGaUpjkK+D3RsBt6FKOA+nT+yYvE34Kr7de85Lqie6cfqDWUsKJs9cLkkwu+wkCxxbj9NyGevrCSLd81Asc0ok54T++2SI291SSMUC6yNgcQKlLpD1PyGaGyh0MGKO/yFlM+7PlARokN03Q/mhCvnb5lpMpf0IlpLVE1HTK4j7b+cR/1mwdQPeFcvpEr8G70zaF8lqXh09Wj+QwuNLGFsRpPstAdUDHFH3ziLf0+ylikzK3BigH++Y1TfH4iXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
