travis:
  secure:
    BINSTAR_TOKEN: RLgt0toUKXPKWXcD37Atz0kr0/G0DG1hyr6fXPzBcyDDQZmvj3d66jK0qQi8kLArfceR9yG79eiOvALW/bXzbvrSeipoFD91Acq58D5JNRhkponeKNRXadJgyoxsrMAzBCozZkB+ImC7HTTBbSDwm22yYGKq6S8eeRuNPOUzC5sO3QIJcaF1T5lstNfkegJFKc1i5ADSTqK9M6/nCPczmuSfV0K1klaID8SZs0h85wjr1iaL7LbCW1J9cEmm1kwRILlk0W9553hn0Y8ui0xNXEJt9HcF21mQUY7TXD+2GYkwD1FvO6gQ+LXhH1bq7R89eyYLmrGGGtPCE0xl60CmHVBmKt+IjdSUzYFtYWto0/cmWF+n1v8RBwPzM3UGgrrB9XcBN2gOAHpex15M6Oz4FiU7HGo9cNkvu2lbi9Z7GXE49zyDpDZIfh+cHOdorG9gOnr8wDA8JvNKS8bpiR6SnTsYNb2hSCAaKDU1ocjVSrDmoBpZIjkXfPeCbmyaM6DwA+r8cbI7bJmn0eLg8ufG4SrqoGis8c1iXRkhOT5DB3+0FbfSX9IPnCdSN3gn0BLL8gU03DwhWvSgH12hJ9fBY2+t7xd1e4BtFg1qkgRp+sHxvEbx2QNeKY0+ipPe09+E5F8pEi+MoSHV0gEYsKn7LSgsbvF02ZkY8ONegAVX5m4=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
