travis:
  secure:
    BINSTAR_TOKEN: SpkYm0M8opuVbUdN8661OZTFJc0MMySIoNE7BFihK3HB1KAkEiuNPv2uUh1FcDjvUgbgSbTCyit/1+QLddVxmxqy30HkMHzXiPVSamLqK/yaLtATo1WhKGe8PMnYwkgGUw/Fi3x9dI2ATjiFznS8X3mlnlxtd1F8VUBrJ8QhQokTILFRs1XH2dlvFYguLOUoqel2eva5jnjVd2O1m5osFcuSbDrShBbeJqmN2w1xC/OgeEP5z5SDswNi85C/RhQkOHC/s3ZTc2eU4Yy+yGq/HXvk0RGliE77//DgnNBjrFvE46Gni0OG4GjB/MzoDMMyUyGMuQn06fqqXIlqLmq9tJOVDnwslY2TbprTYQYrVI7x/ns3W9O/W7tYMHmUvGtDEh03EW9K14jADzdfgaiD/Sg/QCJ7R6UgrzNceLeTuL6fnBGjI6sFHnte4PwB/H+IgTTpwRP7BaoLNPpyzAeI7WcsMp2vPtzyzMVMd2pBj1vDaolKfEED0d2zB20FdmfFRu0Lq0hRF/4uErgQEpbZzcbovFGn8DDrUq66wRC1wdG7/cr7ZHWkjF6M+DW3nqmNZjJ9BJqiHME3FUqFrFbYGnW+P4d06QDfEj0l65NZeEDp+1u0rQQpkAeygrPgTVyEvXoU+lb9EMr0aMGfZlQX8EP9CY+qUqCU1d8LpCuZlV4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
